### ISSUE TITLE
Onboarding feature

### ISSUE THREAD

**Issue by NghiaTranUIT** [toggl-open-source/toggldesktop#3950]
### 📒 Description
Onboarding is a feature to present hints in many places (Timer, Timeline, TimeEntry List, Record Activity, ...) if the user matches some conditions, which is described in https://toggl.invisionapp.com/d/main#/console/19683071/411618499/preview

This ticket would contain all onboarding sub-tickets.

### Approach
- Implement a core logic in the Library (count and keep track activity numbers and determine which condition is fulfilled). Thus, we can reuse it later on other platforms.
- Add some extra columns in User table to keep track the number and the current hint state
- Implement a generic Hint layout on macOS
- Present/dismiss logic and highlight the area for the hint 

### 💻 Environment
Platform: macOS & Library

### Tickets 
- [x] [Onboarding] Hint Popover #3951
- [x] [Onboarding] Core logic library #3952
- [x] [Onboarding] Grey out / Highlight Hint area #3953

**Comment by skel35** [comment]
Had been merged to master as #4068 and then reverted in a430e4c.

**Comment by skel35** [comment]
Merged to master with #4075
