### ISSUE TITLE
Timeline UI on Windows

### ISSUE THREAD

**Issue by skel35** [toggl-open-source/toggldesktop#4269]
### 💻 Environment
Platform: Windows

### 📒 Description
This is a primary issue for the "Timeline UI on Windows" feature.

Designs: https://zpl.io/amkgjjK.

For initial release:
- [x] List/Timeline tabs, use library methods (M also include flag implementation in back office) #4289
- [x] Move Record activity ToggleSwitch from Preferences to Timeline tab (S) #4290 
- [x] Info icon near Record activity with tooltip on hover (tooltip content same as in macOS app) (S) #4290
- [x] add DatePicker and connect days switching to the library methods (S) #4320
- [x] implement the DatePicker style with left/right buttons (M) #4320
- [x] split the main view into 3 blocks (time, time entries, activity) (XS) #4354
- [x] empty states for time entries and activity blocks (S) #4354
- [x] add time marks for time blocks + make every other hour darker (S) #4354
- [x] add Activity visualization (with info on hover) (L) #4370
- [x] display current time (S) #4270
- [x] add basic Time Entry pills visualization with an algorithm for laying them out when TEs overlap (note: designs are logically INCORRECT, refer to macOS app for the correct logic) (L) #4370
- [x] add buttons for creating TEs from gaps (M) #4370
- [x] show full TE details and not just pills if there is no overlap (S) #4370
- [x] add zooming (with +- buttons, Ctrl + and Ctrl - shortcuts) (M) #4408
- [x] add tooltips when hovering over TEs (S) #4409
- [x] open Edit view by click (XS) #4410
- [x] "Record activity" switch in the Timeline tab does not get synchronized with the value in the Preferences #4417
- [x] Timeline tab is shown with `desktop_timeline_ui` flag off #4418

Can be done after the initial release:
- [x] resizing TEs to change the start time or duration (S) #4434
- [ ] dragging TEs to change the start time (M) #4435
- [ ] right-click context menu (items for resolving overlaps (change first entry stop time, change last entry start time), Continue TE, Start from the end of this TE, Stop TE) (not present in designs, refer to macOS app) (S)
- [ ] click-drag to create TE (implement click to create first if click-drag is too difficult to do)
- [ ] onboarding popup (not present in designs)
- [ ] analytics tracking of context menu actions (S)

Optional
- [ ] sticky header when scrolling
- [ ] pinch to zoom

Notes:
- Designs have a horizontal scroll, but there's no need to add it as no users have this many overlapped TEs.
- Feel free to step away from the design or this list if there's a reason to do so. Releasing quicker with high quality is preferred over adhering to spec.

**Comment by GitMurf** [comment]
Wow this looks amazing! I have been waiting SOOOO long for the timeline UI on Windows as I have seen demos of the MAC previously. I am on the Beta build and updated to v7.5.348 but I do not see the option. I noticed in the last release notes it said `Timeline UI view (available only for part of all users now)`.

I also see references to feature flags like `desktop_timeline_ui` mentioned. Is this something I can turn on? Thanks so much for all your awesome hardwork!

**Comment by skel35** [comment]
@GitMurf Drop us a note at support@track.toggl.com with your account's email address and we'll turn it on for you (you'll need to restart the app). Otherwise, we'll enable it for more people in about 1-3 weeks.

**Comment by skel35** [comment]
I'll close this issue as the originally planned scope for the initial release has been implemented. 
Further bugs/features/improvements will be added to and prioritized in the following project https://github.com/toggl-open-source/toggldesktop/projects/24.

Great job @atsvirchkova!
